### ISSUE TITLE
bot not responding to commands

### ISSUE THREAD

**Issue by Marunc1** [nicnacnic/DACBot#1]
Hello, i am trying to test the bot, no errors in the console, bot is online, but not responding to any commands
I tried to play with the intents, but nothing happens.
Any idea?
![Screenshot_7](https://user-images.githubusercontent.com/105013306/210176695-0e08e11b-6447-4f4d-8531-2d82bcb29ee0.png)

**Comment by Marunc1** [comment]
Fixed it by changing the commands.js file
New:
```
 module.exports = (client, alias, roleID, callback) => {
	client.on('message', (message) => {
	  const content = message.content.split(' ');
  
	  if (content.length > 1 && content[0] === `<@${client.user.id}>` && content[1] === alias) {
		if (message.member.hasPermission('ADMINISTRATOR') || message.member.hasPermission('MANAGE_CHANNELS') || message.member.roles.cache.has(roleID)) {
		  if (content[1] === 'volume') {
			if (content.length === 4 && (content[3] > 0 && content[3] <= 100))
			  callback(content[2].substring(content[2].indexOf('!') + 1, content[2].indexOf('>')), content[3], message);
			else
			  message.reply('you provided invalid arguments! Syntax: `@' + client.user.username + ' volume <user> <volumeLevel>`')
		  }
		  else
			callback(message)
		}
		else
		  message.reply(`you do not have permission to execute this command!`)
	  }
	});
  };
  
```
Also, people need this too
npm install @discordjs/opus node-opus ffmpeg
npm install @discordjs/opus node-opus
and install  FFmpeg and add it to PATH environment variable.

**Comment by Jim-m-y** [comment]
I get this error, help pls

E:\downloads\DACBot-main\DACBot-main\node_modules\discord.js\src\client\voice\VoiceConnection.js:303
      this.emit('error', new Error(reason));
                         ^

Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (E:\downloads\DACBot-main\DACBot-main\node_modules\discord.js\src\client\voice\VoiceConnection.js:303:26)
    at E:\downloads\DACBot-main\DACBot-main\node_modules\discord.js\src\client\voice\VoiceConnection.js:324:61
    at Timeout.<anonymous> (E:\downloads\DACBot-main\DACBot-main\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
